---
title: "Network Construction Test"
output: html_notebook
---

### Load the package
```{r}
library(roxygen2)
library(devtools)
setwd("~/Desktop/CloneHunterNew_5/CloneHunterNew/")
devtools::document()

library(tidyverse)
library(foreach)
library(networkD3)
```

### Read in the CellTag Object
```{r}
bam.test.obj <- readRDS("~/Desktop/bam_v123_obj.Rds")
```

### Calculate the Linked list
```{r}
bam.test.obj <- convertCellTagMatrix2LinkList(bam.test.obj)
```

### Get the nodes
```{r}
bam.test.obj <- getNodesfromLinkList(bam.test.obj)
```

### Add additional information
```{r}
additional_data <- data.frame(sample(1:10, size = length(rownames(bam.test.obj@celltag.aggr.final)), replace = TRUE), row.names = rownames(bam.test.obj@celltag.aggr.final))
colnames(additional_data) <- "Cluster"

bam.test.obj <- addData2Nodes(bam.test.obj, additional_data)
```

### Network visualization and plot

```{r, fig.width=10, fig.height=10}
bam.test.obj <- drawSubnet(tag = "CellTagV1_2", overlay = "Cluster", celltag.obj = bam.test.obj)
bam.test.obj@network
saveNetwork(bam.test.obj@network, "~/Desktop/hf1.d15.network.construction.html")
```

### Stacked bar charts
```{r}
bar.data <- bam.test.obj@celltag.aggr.final
bar.data$Cell.BC <- rownames(bar.data)

bar.data <- gather(bar.data, key = "CellTag", value = "Clone", 1:3, na.rm = FALSE)
```

### ggplot
```{r}
ggplot(data = bar.data) + 
  geom_bar(mapping = aes(x = CellTag, fill = factor(Clone)), position = "fill", show.legend = FALSE) + 
  scale_y_continuous(labels = scales::percent_format()) +
  theme_bw()
```


